In [3]:
import pandas as pd
import numpy as np

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [31]:
data = {
    'col1': np.random.randint(0, 100, 6),
    'col2': np.random.randint(0, 100, 6),
    'col3': np.random.randint(0, 100, 6),
    'col4': np.random.randint(0, 100, 6)
}
df = pd.DataFrame(data)
df.set_index('col1', inplace=True)
display(df)



data2 = {
    'A': np.random.randint(0, 100, 3),
    'B': np.random.randint(0, 100, 3),
    'C': np.random.randint(0, 100, 3),
}
df2 = pd.DataFrame(data2)
df2.index = ['X', 'Y', 'Z']
display(df2)
print(f"Accessing the element at row 'Y' and column 'B'>> {df2['B']['Y']}")

      col2  col3  col4
col1
21      54    14    68
37      36    77    14
87      48    86    47
76      49     4    23
66      41    48     7
37      78    18     7

    A   B   C
X  59  72  70
Y  40   1  75
Z  56  65   1

Accessing the element at row 'Y' and column 'B'>> 1

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [38]:
data = {
    'a': np.random.randint(1, 10, 5),
    'b': np.random.randint(1, 10, 5),
    'c': np.random.randint(1, 10, 5),
}

df = pd.DataFrame(data)
print(f"orignal dataframe: \n {df}")
df["Product"] = (df['a']*df['b'])
print(f"Dataframe with the produt column: \n {df}")

# Row-wise and Column-wise sum
print(f"Row-wise sum:\n{df.sum(axis=0)}")
print(f"Column-wise sum:\n{df.sum(axis=1)}")

orignal dataframe:
    a  b  c
0  2  8  4
1  3  8  3
2  6  7  2
3  7  2  6
4  7  1  8
Dataframe with the produt column:
    a  b  c  Product
0  2  8  4       16
1  3  8  3       24
2  6  7  2       42
3  7  2  6       14
4  7  1  8        7
Row-wise sum:
a           25
b           26
c           23
Product    103
dtype: int64
Column-wise sum:
0    30
1    38
2    57
3    29
4    23
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [47]:
data = {
    'a': np.random.randint(1, 10, 5),
    'b': np.random.randint(1, 10, 5),
    'c': np.random.randint(1, 10, 5),
}

df = pd.DataFrame(data)
print(f"orignal dataframe: \n {df}")

#Introducing NaN values

df.loc[2, 'a'] = np.nan
df.loc[3, 'b'] = np.nan
df.loc[3, 'c'] = np.nan
df.loc[1, 'c'] = np.nan
print(f"Dataframe with Nans: \n{df}")
#filling NaNs with mean of respective coloumns

df['a'] = df['a'].fillna(df['a'].mean()).astype(int)
df['b'] = df['b'].fillna(df['b'].mean()).astype(int)
df['c'] = df['c'].fillna(df['c'].mean()).astype(int)



# dataframe after filling the Nans

display(df)

orignal dataframe:
    a  b  c
0  2  5  3
1  3  5  5
2  6  6  9
3  8  1  5
4  6  4  8
Dataframe with Nans:
     a    b    c
0  2.0  5.0  3.0
1  3.0  5.0  NaN
2  NaN  6.0  9.0
3  8.0  NaN  NaN
4  6.0  4.0  8.0

   a  b  c
0  2  5  3
1  3  5  6
2  4  6  9
3  8  5  6
4  6  4  8

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [68]:
data = {
    'Category': np.random.choice(['A', 'B', 'C'], 150),
    'Value': np.random.randint(1, 100, 150)
}

df = pd.DataFrame(data)
display(df.head())
summary= df.groupby('Category')['Value'].agg(['sum', 'mean'])


print(f"Summary statistics for each category: \n{summary}")


data2 = {
    'Product': np.random.choice(['PD1', 'PD2', 'PD3', 'PD4'], 150),
    'Category': np.random.choice(['A', 'B', 'C', 'D'], 150),
    'Sales': np.random.randint(1, 100, 150)
}
df2 = pd.DataFrame(data2)
display(df2.head())

groupby_cat = df2.groupby('Category')['Sales'].sum()
print(f"Total sales per category: \n{groupby_cat}")

  Category  Value
0        C     47
1        A     93
2        A     95
3        C     70
4        B     59

Summary statistics for each category:
           sum       mean
Category
A         2321  49.382979
B         2100  47.727273
C         3010  51.016949

  Product Category  Sales
0     PD4        C     89
1     PD3        D     44
2     PD2        C     38
3     PD4        D     94
4     PD4        A     48

Total sales per category:
Category
A    1764
B    1826
C    1927
D    2127
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [85]:
data = {
    'Category': np.random.choice(['A', 'B', 'C', 'E', 'F'], 150),
    'Value': np.random.randint(1, 100, 150)
}
data2 = {
    'Product': np.random.choice(['PD1', 'PD2', 'PD3', 'PD4'], 150),
    'Category': np.random.choice(['A', 'B', 'C', 'D', 'G'], 150),
    'Sales': np.random.randint(1, 100, 150)
}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data2)
merged_df = pd.merge(df1, df2, on='Category', how='inner')
print(f"merged dataFrame: \n{merged_df}")

concat_df_row = pd.concat([df1, df2], axis=0)
concat_df_col = pd.concat([df1, df2], axis=1)
print(f"concat over row: \n{concat_df_row}")
print(f"concat over col: \n{concat_df_col}")

merged dataFrame:
     Category  Value Product  Sales
0           A     69     PD4     65
1           A     69     PD2     44
2           A     69     PD1     16
3           A     69     PD3      8
4           A     69     PD3      9
...       ...    ...     ...    ...
2420        C     22     PD4     14
2421        C     22     PD3      3
2422        C     22     PD4     68
2423        C     22     PD2     25
2424        C     22     PD2     67

[2425 rows x 4 columns]
concat over row:
    Category  Value Product  Sales
0          A   69.0     NaN    NaN
1          F    1.0     NaN    NaN
2          E   17.0     NaN    NaN
3          C   77.0     NaN    NaN
4          F   34.0     NaN    NaN
..       ...    ...     ...    ...
145        A    NaN     PD4   64.0
146        A    NaN     PD3    4.0
147        D    NaN     PD3   68.0
148        G    NaN     PD1   29.0
149        A    NaN     PD2   54.0

[300 rows x 4 columns]
concat over col:
    Category  Value Product Category  Sales
0          A     69     PD2        D     91
1          F      1     PD4        A     65
2          E     17     PD1        D     99
3          C     77     PD1        D      9
4          F     34     PD4        B     37
..       ...    ...     ...      ...    ...
145        A     38     PD4        A     64
146        B     50     PD3        A      4
147        C     87     PD3        D     68
148        F     49     PD1        G     29
149        C     22     PD2        A     54

[150 rows x 5 columns]